import type { Metadata } from "next";
import Script from "next/script";
import { GoogleTagManager } from '@next/third-parties/google';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="h-full relative">
      <head>
        {/* Google Fonts - Poppins */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link 
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" 
          rel="stylesheet" 
        />

        {/* jBox CSS - External Resource */}
        <link 
          href="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v1.3.3/dist/jBox.all.min.css" 
          rel="stylesheet" 
        />
        
        {/* OneTrust Cookies Consent */}
        <Script 
          src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js" 
          data-document-language="true" 
          type="text/javascript" 
          charSet="UTF-8" 
          data-domain-script="d57e5842-f42f-46bc-a4ea-4a82bd82322c"
          strategy="beforeInteractive"
        />
        <Script id="optanon-wrapper" strategy="beforeInteractive">
          {`function OptanonWrapper() { }`}
        </Script>
      </head>
      <body
        className="font-sans antialiased"
      >
        {children}
        <GoogleTagManager gtmId="GTM-WCL8QV" />
      </body>
    </html>
  );
}
